# Site settings
title: KimSoungRyoul
description: KimSoungRyoul's CV
favicon: /assets/img/avatar.png
baseurl: /resume
url: https://kimsoungryoul.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 김성렬 (SoungRyoul Kim)
  title: Python(Java) Backend Developer
  address: Seoul
  email: KimSoungRyoul@gmail.com
  link: https://medium.com/@soungryoul.kim
  weibo:
  github: KimSoungRyoul-Portfolio
  linkedin: soungryoul-kim-558a14156
  medium: 'soungryoul.kim'
  gavatar: /assets/img/avatar.png

  workHistory:
    - work1:
      company: "요기요:Vendor(공급자) 관리 서비스 개발"
      location: Seoul
      title: DeliveryHero Korea (Yogiyo)
      started: 2020
      duration: (2019 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: "요기요: Vendor(공급자) 서비스 Maintenance Squad"
      location: Seoul
      title: DeliveryHero Korea (Yogiyo)
      started: 2019
      duration: (2020.06- 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: "요기요: Yogiyo Maintenance Squad"
      location: Seoul
      title: DeliveryHero Korea (Yogiyo)
      started: 2019
      duration: (2009 - 2012)
      description: "* 기초적인 시스템 ㄴㅇㄹㄴㅇㄹ"




  studyHistory:
    - study1:
      organization: 오픈소스pytest
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description.sdfsdfsdfsdf

  languages:
    - language1:
      name: Python
      frameworkList:
        - framework:
          name: Django
        - framework:
          name: DjangoRestFramework
        - framework:
          name: FastAPI,Pydentic
    - language2:
      name: Java
      frameworkList:
        - framework1:
          name: Spring
    - language3:
      name: Docker K8s
      frameworkList:
        - framework1:
          name: AWS

